runtime: python310

default_expiration: 1s

handlers:
  - url: /api/.*
    script: auto
  - url: /
    static_files: static/lp.html
    upload: static/lp.html
  - url: /
    static_dir: static

automatic_scaling:
    max_instances: 1
