name: CD-deployment

on:  
  workflow_dispatch:

jobs:
  deploy-to-gae:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - run: cp -r backend/* gae
    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - uses: 'google-github-actions/deploy-appengine@v1'
      with:
        working_directory: gae
        version: the-only-one
